name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Solarize
      run: ./solarize.sh
    
    - name: Autogen
      run: |
        export _arcdir=$(ls | grep "arc-theme-" | tail -1)
        cd "${_arcdir}"
        ./autogen.sh --prefix=/usr --with-gnome-shell=3.32 --with-gtk3=3.24
